<?php
return "INSERT INTO `countries` (`ID`, `lang`, `lang_name`, `country_alpha2_code`, `country_alpha3_code`, `country_numeric_code`, `country_name`) VALUES
(2, 'en', 'english', 'AD', 'AND', '20', 'Andorra'),
(3, 'en', 'english', 'AE', 'ARE', '784', 'United Arab Emirates'),
(4, 'en', 'english', 'AF', 'AFG', '4', 'Afghanistan'),
(5, 'en', 'english', 'AG', 'ATG', '28', 'Antigua and Barbuda'),
(6, 'en', 'english', 'AI', 'AIA', '660', 'Anguilla'),
(7, 'en', 'english', 'AL', 'ALB', '8', 'Albania'),
(8, 'en', 'english', 'AM', 'ARM', '51', 'Armenia'),
(9, 'en', 'english', 'AO', 'AGO', '24', 'Angola'),
(10, 'en', 'english', 'AQ', 'ATA', '10', 'Antarctica'),
(11, 'en', 'english', 'AR', 'ARG', '32', 'Argentina'),
(12, 'en', 'english', 'AS', 'ASM', '16', 'American Samoa'),
(13, 'en', 'english', 'AT', 'AUT', '40', 'Austria'),
(14, 'en', 'english', 'AU', 'AUS', '36', 'Australia'),
(15, 'en', 'english', 'AW', 'ABW', '533', 'Aruba'),
(16, 'en', 'english', 'AX', 'ALA', '248', 'Aland Islands'),
(17, 'en', 'english', 'AZ', 'AZE', '31', 'Azerbaijan'),
(18, 'en', 'english', 'BA', 'BIH', '70', 'Bosnia and Herzegovina'),
(19, 'en', 'english', 'BB', 'BRB', '52', 'Barbados'),
(20, 'en', 'english', 'BD', 'BGD', '50', 'Bangladesh'),
(21, 'en', 'english', 'BE', 'BEL', '56', 'Belgium'),
(22, 'en', 'english', 'BF', 'BFA', '854', 'Burkina Faso'),
(23, 'en', 'english', 'BG', 'BGR', '100', 'Bulgaria'),
(24, 'en', 'english', 'BH', 'BHR', '48', 'Bahrain'),
(25, 'en', 'english', 'BI', 'BDI', '108', 'Burundi'),
(26, 'en', 'english', 'BJ', 'BEN', '204', 'Benin'),
(27, 'en', 'english', 'BL', 'BLM', '652', 'Saint Barthelemy'),
(28, 'en', 'english', 'BM', 'BMU', '60', 'Bermuda'),
(29, 'en', 'english', 'BN', 'BRN', '96', 'Brunei Darussalam'),
(30, 'en', 'english', 'BO', 'BOL', '68', 'Bolivia, Plurinational State of'),
(31, 'en', 'english', 'BQ', 'BES', '535', 'Bonaire, Sint Eustatius and Saba'),
(32, 'en', 'english', 'BR', 'BRA', '76', 'Brazil'),
(33, 'en', 'english', 'BS', 'BHS', '44', 'Bahamas'),
(34, 'en', 'english', 'BT', 'BTN', '64', 'Bhutan'),
(35, 'en', 'english', 'BV', 'BVT', '74', 'Bouvet Island'),
(36, 'en', 'english', 'BW', 'BWA', '72', 'Botswana'),
(37, 'en', 'english', 'BY', 'BLR', '112', 'Belarus'),
(38, 'en', 'english', 'BZ', 'BLZ', '84', 'Belize'),
(39, 'en', 'english', 'CA', 'CAN', '124', 'Canada'),
(40, 'en', 'english', 'CC', 'CCK', '166', 'Cocos (Keeling) Islands'),
(41, 'en', 'english', 'CD', 'COD', '180', 'Congo, The Democratic Republic of The'),
(42, 'en', 'english', 'CF', 'CAF', '140', 'Central African Republic'),
(43, 'en', 'english', 'CG', 'COG', '178', 'Congo'),
(44, 'en', 'english', 'CH', 'CHE', '756', 'Switzerland'),
(45, 'en', 'english', 'CI', 'CIV', '384', 'Cote D\'ivoire'),
(46, 'en', 'english', 'CK', 'COK', '184', 'Cook Islands'),
(47, 'en', 'english', 'CL', 'CHL', '152', 'Chile'),
(48, 'en', 'english', 'CM', 'CMR', '120', 'Cameroon'),
(49, 'en', 'english', 'CN', 'CHN', '156', 'China'),
(50, 'en', 'english', 'CO', 'COL', '170', 'Colombia'),
(51, 'en', 'english', 'CR', 'CRI', '188', 'Costa Rica'),
(52, 'en', 'english', 'CU', 'CUB', '192', 'Cuba'),
(53, 'en', 'english', 'CV', 'CPV', '132', 'Cabo Verde'),
(54, 'en', 'english', 'CW', 'CUW', '531', 'Curacao'),
(55, 'en', 'english', 'CX', 'CXR', '162', 'Christmas Island'),
(56, 'en', 'english', 'CY', 'CYP', '196', 'Cyprus'),
(57, 'en', 'english', 'CZ', 'CZE', '203', 'Czech Republic'),
(58, 'en', 'english', 'DE', 'DEU', '276', 'Germany'),
(59, 'en', 'english', 'DJ', 'DJI', '262', 'Djibouti'),
(60, 'en', 'english', 'DK', 'DNK', '208', 'Denmark'),
(61, 'en', 'english', 'DM', 'DMA', '212', 'Dominica'),
(62, 'en', 'english', 'DO', 'DOM', '214', 'Dominican Republic'),
(63, 'en', 'english', 'DZ', 'DZA', '12', 'Algeria'),
(64, 'en', 'english', 'EC', 'ECU', '218', 'Ecuador'),
(65, 'en', 'english', 'EE', 'EST', '233', 'Estonia'),
(66, 'en', 'english', 'EG', 'EGY', '818', 'Egypt'),
(67, 'en', 'english', 'EH', 'ESH', '732', 'Western Sahara'),
(68, 'en', 'english', 'ER', 'ERI', '232', 'Eritrea'),
(69, 'en', 'english', 'ES', 'ESP', '724', 'Spain'),
(70, 'en', 'english', 'ET', 'ETH', '231', 'Ethiopia'),
(71, 'en', 'english', 'FI', 'FIN', '246', 'Finland'),
(72, 'en', 'english', 'FJ', 'FJI', '242', 'Fiji'),
(73, 'en', 'english', 'FK', 'FLK', '238', 'Falkland Islands (Malvinas)'),
(74, 'en', 'english', 'FM', 'FSM', '583', 'Micronesia, Federated States of'),
(75, 'en', 'english', 'FO', 'FRO', '234', 'Faroe Islands'),
(76, 'en', 'english', 'FR', 'FRA', '250', 'France'),
(77, 'en', 'english', 'GA', 'GAB', '266', 'Gabon'),
(78, 'en', 'english', 'GB', 'GBR', '826', 'United Kingdom'),
(79, 'en', 'english', 'GD', 'GRD', '308', 'Grenada'),
(80, 'en', 'english', 'GE', 'GEO', '268', 'Georgia'),
(81, 'en', 'english', 'GF', 'GUF', '254', 'French Guiana'),
(82, 'en', 'english', 'GG', 'GGY', '831', 'Guernsey'),
(83, 'en', 'english', 'GH', 'GHA', '288', 'Ghana'),
(84, 'en', 'english', 'GI', 'GIB', '292', 'Gibraltar'),
(85, 'en', 'english', 'GL', 'GRL', '304', 'Greenland'),
(86, 'en', 'english', 'GM', 'GMB', '270', 'Gambia'),
(87, 'en', 'english', 'GN', 'GIN', '324', 'Guinea'),
(88, 'en', 'english', 'GP', 'GLP', '312', 'Guadeloupe'),
(89, 'en', 'english', 'GQ', 'GNQ', '226', 'Equatorial Guinea'),
(90, 'en', 'english', 'GR', 'GRC', '300', 'Greece'),
(91, 'en', 'english', 'GS', 'SGS', '239', 'South Georgia and The South Sandwich Islands'),
(92, 'en', 'english', 'GT', 'GTM', '320', 'Guatemala'),
(93, 'en', 'english', 'GU', 'GUM', '316', 'Guam'),
(94, 'en', 'english', 'GW', 'GNB', '624', 'Guinea-Bissau'),
(95, 'en', 'english', 'GY', 'GUY', '328', 'Guyana'),
(96, 'en', 'english', 'HK', 'HKG', '344', 'Hong Kong'),
(97, 'en', 'english', 'HM', 'HMD', '334', 'Heard Island and Mcdonald Islands'),
(98, 'en', 'english', 'HN', 'HND', '340', 'Honduras'),
(99, 'en', 'english', 'HR', 'HRV', '191', 'Croatia'),
(100, 'en', 'english', 'HT', 'HTI', '332', 'Haiti'),
(101, 'en', 'english', 'HU', 'HUN', '348', 'Hungary'),
(102, 'en', 'english', 'ID', 'IDN', '360', 'Indonesia'),
(103, 'en', 'english', 'IE', 'IRL', '372', 'Ireland'),
(104, 'en', 'english', 'IL', 'ISR', '376', 'Israel'),
(105, 'en', 'english', 'IM', 'IMN', '833', 'Isle of Man'),
(106, 'en', 'english', 'IN', 'IND', '356', 'India'),
(107, 'en', 'english', 'IO', 'IOT', '86', 'British Indian Ocean Territory'),
(108, 'en', 'english', 'IQ', 'IRQ', '368', 'Iraq'),
(109, 'en', 'english', 'IR', 'IRN', '364', 'Iran, Islamic Republic of'),
(110, 'en', 'english', 'IS', 'ISL', '352', 'Iceland'),
(111, 'en', 'english', 'IT', 'ITA', '380', 'Italy'),
(112, 'en', 'english', 'JE', 'JEY', '832', 'Jersey'),
(113, 'en', 'english', 'JM', 'JAM', '388', 'Jamaica'),
(114, 'en', 'english', 'JO', 'JOR', '400', 'Jordan'),
(115, 'en', 'english', 'JP', 'JPN', '392', 'Japan'),
(116, 'en', 'english', 'KE', 'KEN', '404', 'Kenya'),
(117, 'en', 'english', 'KG', 'KGZ', '417', 'Kyrgyzstan'),
(118, 'en', 'english', 'KH', 'KHM', '116', 'Cambodia'),
(119, 'en', 'english', 'KI', 'KIR', '296', 'Kiribati'),
(120, 'en', 'english', 'KM', 'COM', '174', 'Comoros'),
(121, 'en', 'english', 'KN', 'KNA', '659', 'Saint Kitts and Nevis'),
(122, 'en', 'english', 'KP', 'PRK', '408', 'Korea, Democratic People\'s Republic of'),
(123, 'en', 'english', 'KR', 'KOR', '410', 'Korea, Republic of'),
(124, 'en', 'english', 'KW', 'KWT', '414', 'Kuwait'),
(125, 'en', 'english', 'KY', 'CYM', '136', 'Cayman Islands'),
(126, 'en', 'english', 'KZ', 'KAZ', '398', 'Kazakhstan'),
(127, 'en', 'english', 'LA', 'LAO', '418', 'Lao People\'s Democratic Republic'),
(128, 'en', 'english', 'LB', 'LBN', '422', 'Lebanon'),
(129, 'en', 'english', 'LC', 'LCA', '662', 'Saint Lucia'),
(130, 'en', 'english', 'LI', 'LIE', '438', 'Liechtenstein'),
(131, 'en', 'english', 'LK', 'LKA', '144', 'Sri Lanka'),
(132, 'en', 'english', 'LR', 'LBR', '430', 'Liberia'),
(133, 'en', 'english', 'LS', 'LSO', '426', 'Lesotho'),
(134, 'en', 'english', 'LT', 'LTU', '440', 'Lithuania'),
(135, 'en', 'english', 'LU', 'LUX', '442', 'Luxembourg'),
(136, 'en', 'english', 'LV', 'LVA', '428', 'Latvia'),
(137, 'en', 'english', 'LY', 'LBY', '434', 'Libya'),
(138, 'en', 'english', 'MA', 'MAR', '504', 'Morocco'),
(139, 'en', 'english', 'MC', 'MCO', '492', 'Monaco'),
(140, 'en', 'english', 'MD', 'MDA', '498', 'Moldova, Republic of'),
(141, 'en', 'english', 'ME', 'MNE', '499', 'Montenegro'),
(142, 'en', 'english', 'MF', 'MAF', '663', 'Saint Martin (French Part)'),
(143, 'en', 'english', 'MG', 'MDG', '450', 'Madagascar'),
(144, 'en', 'english', 'MH', 'MHL', '584', 'Marshall Islands'),
(145, 'en', 'english', 'MK', 'MKD', '807', 'North Macedonia'),
(146, 'en', 'english', 'ML', 'MLI', '466', 'Mali'),
(147, 'en', 'english', 'MM', 'MMR', '104', 'Myanmar'),
(148, 'en', 'english', 'MN', 'MNG', '496', 'Mongolia'),
(149, 'en', 'english', 'MO', 'MAC', '446', 'Macao'),
(150, 'en', 'english', 'MP', 'MNP', '580', 'Northern Mariana Islands'),
(151, 'en', 'english', 'MQ', 'MTQ', '474', 'Martinique'),
(152, 'en', 'english', 'MR', 'MRT', '478', 'Mauritania'),
(153, 'en', 'english', 'MS', 'MSR', '500', 'Montserrat'),
(154, 'en', 'english', 'MT', 'MLT', '470', 'Malta'),
(155, 'en', 'english', 'MU', 'MUS', '480', 'Mauritius'),
(156, 'en', 'english', 'MV', 'MDV', '462', 'Maldives'),
(157, 'en', 'english', 'MW', 'MWI', '454', 'Malawi'),
(158, 'en', 'english', 'MX', 'MEX', '484', 'Mexico'),
(159, 'en', 'english', 'MY', 'MYS', '458', 'Malaysia'),
(160, 'en', 'english', 'MZ', 'MOZ', '508', 'Mozambique'),
(161, 'en', 'english', 'NA', 'NAM', '516', 'Namibia'),
(162, 'en', 'english', 'NC', 'NCL', '540', 'New Caledonia'),
(163, 'en', 'english', 'NE', 'NER', '562', 'Niger'),
(164, 'en', 'english', 'NF', 'NFK', '574', 'Norfolk Island'),
(165, 'en', 'english', 'NG', 'NGA', '566', 'Nigeria'),
(166, 'en', 'english', 'NI', 'NIC', '558', 'Nicaragua'),
(167, 'en', 'english', 'NL', 'NLD', '528', 'Netherlands'),
(168, 'en', 'english', 'NO', 'NOR', '578', 'Norway'),
(169, 'en', 'english', 'NP', 'NPL', '524', 'Nepal'),
(170, 'en', 'english', 'NR', 'NRU', '520', 'Nauru'),
(171, 'en', 'english', 'NU', 'NIU', '570', 'Niue'),
(172, 'en', 'english', 'NZ', 'NZL', '554', 'New Zealand'),
(173, 'en', 'english', 'OM', 'OMN', '512', 'Oman'),
(174, 'en', 'english', 'PA', 'PAN', '591', 'Panama'),
(175, 'en', 'english', 'PE', 'PER', '604', 'Peru'),
(176, 'en', 'english', 'PF', 'PYF', '258', 'French Polynesia'),
(177, 'en', 'english', 'PG', 'PNG', '598', 'Papua New Guinea'),
(178, 'en', 'english', 'PH', 'PHL', '608', 'Philippines'),
(179, 'en', 'english', 'PK', 'PAK', '586', 'Pakistan'),
(180, 'en', 'english', 'PL', 'POL', '616', 'Poland'),
(181, 'en', 'english', 'PM', 'SPM', '666', 'Saint Pierre and Miquelon'),
(182, 'en', 'english', 'PN', 'PCN', '612', 'Pitcairn'),
(183, 'en', 'english', 'PR', 'PRI', '630', 'Puerto Rico'),
(184, 'en', 'english', 'PS', 'PSE', '275', 'Palestine, State of'),
(185, 'en', 'english', 'PT', 'PRT', '620', 'Portugal'),
(186, 'en', 'english', 'PW', 'PLW', '585', 'Palau'),
(187, 'en', 'english', 'PY', 'PRY', '600', 'Paraguay'),
(188, 'en', 'english', 'QA', 'QAT', '634', 'Qatar'),
(189, 'en', 'english', 'RE', 'REU', '638', 'Reunion'),
(190, 'en', 'english', 'RO', 'ROU', '642', 'Romania'),
(191, 'en', 'english', 'RS', 'SRB', '688', 'Serbia'),
(192, 'en', 'english', 'RU', 'RUS', '643', 'Russian Federation'),
(193, 'en', 'english', 'RW', 'RWA', '646', 'Rwanda'),
(194, 'en', 'english', 'SA', 'SAU', '682', 'Saudi Arabia'),
(195, 'en', 'english', 'SB', 'SLB', '90', 'Solomon Islands'),
(196, 'en', 'english', 'SC', 'SYC', '690', 'Seychelles'),
(197, 'en', 'english', 'SD', 'SDN', '729', 'Sudan'),
(198, 'en', 'english', 'SE', 'SWE', '752', 'Sweden'),
(199, 'en', 'english', 'SG', 'SGP', '702', 'Singapore'),
(200, 'en', 'english', 'SH', 'SHN', '654', 'Saint Helena, Ascension and Tristan Da Cunha'),
(201, 'en', 'english', 'SI', 'SVN', '705', 'Slovenia'),
(202, 'en', 'english', 'SJ', 'SJM', '744', 'Svalbard and Jan Mayen'),
(203, 'en', 'english', 'SK', 'SVK', '703', 'Slovakia'),
(204, 'en', 'english', 'SL', 'SLE', '694', 'Sierra Leone'),
(205, 'en', 'english', 'SM', 'SMR', '674', 'San Marino'),
(206, 'en', 'english', 'SN', 'SEN', '686', 'Senegal'),
(207, 'en', 'english', 'SO', 'SOM', '706', 'Somalia'),
(208, 'en', 'english', 'SR', 'SUR', '740', 'Suriname'),
(209, 'en', 'english', 'SS', 'SSD', '728', 'South Sudan'),
(210, 'en', 'english', 'ST', 'STP', '678', 'Sao Tome and Principe'),
(211, 'en', 'english', 'SV', 'SLV', '222', 'El Salvador'),
(212, 'en', 'english', 'SX', 'SXM', '534', 'Sint Maarten (Dutch Part)'),
(213, 'en', 'english', 'SY', 'SYR', '760', 'Syrian Arab Republic'),
(214, 'en', 'english', 'SZ', 'SWZ', '748', 'Swaziland'),
(215, 'en', 'english', 'TC', 'TCA', '796', 'Turks and Caicos Islands'),
(216, 'en', 'english', 'TD', 'TCD', '148', 'Chad'),
(217, 'en', 'english', 'TF', 'ATF', '260', 'French Southern Territories'),
(218, 'en', 'english', 'TG', 'TGO', '768', 'Togo'),
(219, 'en', 'english', 'TH', 'THA', '764', 'Thailand'),
(220, 'en', 'english', 'TJ', 'TJK', '762', 'Tajikistan'),
(221, 'en', 'english', 'TK', 'TKL', '772', 'Tokelau'),
(222, 'en', 'english', 'TL', 'TLS', '626', 'Timor-Leste'),
(223, 'en', 'english', 'TM', 'TKM', '795', 'Turkmenistan'),
(224, 'en', 'english', 'TN', 'TUN', '788', 'Tunisia'),
(225, 'en', 'english', 'TO', 'TON', '776', 'Tonga'),
(226, 'en', 'english', 'TR', 'TUR', '792', 'Turkey'),
(227, 'en', 'english', 'TT', 'TTO', '780', 'Trinidad and Tobago'),
(228, 'en', 'english', 'TV', 'TUV', '798', 'Tuvalu'),
(229, 'en', 'english', 'TW', 'TWN', '158', 'Taiwan, Province of China'),
(230, 'en', 'english', 'TZ', 'TZA', '834', 'Tanzania, United Republic of'),
(231, 'en', 'english', 'UA', 'UKR', '804', 'Ukraine'),
(232, 'en', 'english', 'UG', 'UGA', '800', 'Uganda'),
(233, 'en', 'english', 'UM', 'UMI', '581', 'United States Minor Outlying Islands'),
(234, 'en', 'english', 'US', 'USA', '840', 'United States'),
(235, 'en', 'english', 'UY', 'URY', '858', 'Uruguay'),
(236, 'en', 'english', 'UZ', 'UZB', '860', 'Uzbekistan'),
(237, 'en', 'english', 'VA', 'VAT', '336', 'Holy See'),
(238, 'en', 'english', 'VC', 'VCT', '670', 'Saint Vincent and The Grenadines'),
(239, 'en', 'english', 'VE', 'VEN', '862', 'Venezuela, Bolivarian Republic of'),
(240, 'en', 'english', 'VG', 'VGB', '92', 'Virgin Islands, British'),
(241, 'en', 'english', 'VI', 'VIR', '850', 'Virgin Islands, U.S.'),
(242, 'en', 'english', 'VN', 'VNM', '704', 'Viet Nam'),
(243, 'en', 'english', 'VU', 'VUT', '548', 'Vanuatu'),
(244, 'en', 'english', 'WF', 'WLF', '876', 'Wallis and Futuna'),
(245, 'en', 'english', 'WS', 'WSM', '882', 'Samoa'),
(246, 'en', 'english', 'YE', 'YEM', '887', 'Yemen'),
(247, 'en', 'english', 'YT', 'MYT', '175', 'Mayotte'),
(248, 'en', 'english', 'ZA', 'ZAF', '710', 'South Africa'),
(249, 'en', 'english', 'ZM', 'ZMB', '894', 'Zambia'),
(250, 'en', 'english', 'ZW', 'ZWE', '716', 'Zimbabwe');";